MySQL:
  host: localhost
  port: 3306
  database: DataBaseName
  table: TableName
  user: username
  password: password

debug: false
mode: lgw

item:
  material: PAPER
  name: 交換用チケット
  
sound:
  error: true
  success: true
  congratulations: true